Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 55

Metrics/MethodLength:
  Max: 45

Style/TrivialAccessors:
  AllowPredicates: true

AllCops:
  Exclude:
    - '**/spec_helper.rb'
    - '**/ui_*.rb'
